// Firebase configuration for uber_admin_panel.
//
// GENERATED by tools/configure_firebase.py from
//   android/app/google-services.json  (Android options)
//   the Firebase Web app config        (Web options)
//
// Do not edit by hand. After downloading a new google-services.json run:
//   python3 tools/configure_firebase.py --google-services <path> --web-config <path>
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'register an iOS app in the Firebase console and add its options here.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'register a macOS app in the Firebase console and add its options here.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'register a Windows app in the Firebase console and add its options here.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'Firebase does not support Linux desktop apps.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase project: everyone-2de50
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: '311663641676',
    projectId: 'everyone-2de50',
    authDomain: 'everyone-2de50.firebaseapp.com',
    databaseURL: 'https://everyone-2de50-default-rtdb.firebaseio.com',
    storageBucket: 'everyone-2de50.appspot.com',
  );

  /// Android package: com.example.uber_admin_panel
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTI-xVId1DTz9DS0-LEJZhF-eAFv352c',
    appId: '1:311663641676:android:e050637aae25e7aab8a0e9',
    messagingSenderId: '311663641676',
    projectId: 'everyone-2de50',
    databaseURL: 'https://everyone-2de50-default-rtdb.firebaseio.com',
    storageBucket: 'everyone-2de50.appspot.com',
  );
}
