#!/usr/bin/env python3
"""Point the three Flutter apps of this repository at a Firebase project.

What it does, for every selected app (default: all three):

1. Optionally copies a freshly downloaded ``google-services.json`` into
   ``<app>/android/app/google-services.json``.
2. Reads that file, picks the Android client whose ``package_name`` matches the
   app's ``applicationId`` (taken from ``android/app/build.gradle``) and writes
   ``<app>/lib/firebase_options.dart`` with the Android options and – if a web
   config is supplied – the Web options.

The generated Dart file is the same shape as the one produced by the
FlutterFire CLI, so ``flutterfire configure`` can still be used later.

Usage examples::

    # After downloading google-services.json from the Firebase console
    python3 tools/configure_firebase.py \
        --google-services ~/Downloads/google-services.json \
        --web-config ~/Downloads/firebase_web_config.txt

    # Regenerate lib/firebase_options.dart from the JSON files already in the repo
    python3 tools/configure_firebase.py

    # Only one app
    python3 tools/configure_firebase.py --apps uber_admin_panel

The ``--web-config`` file may contain either JSON or the JavaScript snippet
shown in the Firebase console (``const firebaseConfig = { apiKey: "...", ... }``).
Only Python 3.8+ (standard library) is required.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_APPS = ["uber_users_app", "uber_drivers_app", "uber_admin_panel"]

WEB_API_KEY_PLACEHOLDER = "YOUR_WEB_API_KEY"
WEB_APP_ID_PLACEHOLDER = "YOUR_WEB_APP_ID"

DART_TEMPLATE = """\
// Firebase configuration for {app_name}.
//
// GENERATED by tools/configure_firebase.py from
//   android/app/google-services.json  (Android options)
//   the Firebase Web app config        (Web options)
//
// Do not edit by hand. After downloading a new google-services.json run:
//   python3 tools/configure_firebase.py --google-services <path> --web-config <path>
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'register an iOS app in the Firebase console and add its options here.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'register a macOS app in the Firebase console and add its options here.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'register a Windows app in the Firebase console and add its options here.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'Firebase does not support Linux desktop apps.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }}
  }}

  /// Firebase project: {project_id}
  static const FirebaseOptions web = FirebaseOptions(
{web_fields}
  );

  /// Android package: {package_name}
  static const FirebaseOptions android = FirebaseOptions(
{android_fields}
  );
}}
"""


class ConfigError(Exception):
    """Raised for user-facing configuration problems."""


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def read_application_id(app_dir: Path) -> str:
    """Return the Android applicationId declared in android/app/build.gradle(.kts)."""
    for name in ("build.gradle", "build.gradle.kts"):
        gradle = app_dir / "android" / "app" / name
        if not gradle.exists():
            continue
        match = re.search(r'applicationId\s*=?\s*["\']([^"\']+)["\']', gradle.read_text("utf-8"))
        if match:
            return match.group(1)
        raise ConfigError(f"{gradle}: could not find applicationId")
    raise ConfigError(f"{app_dir}: android/app/build.gradle not found")


def load_google_services(path: Path) -> dict:
    try:
        data = json.loads(path.read_text("utf-8"))
    except FileNotFoundError:
        raise ConfigError(f"{path} does not exist") from None
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON: {exc}") from None
    if "project_info" not in data or "client" not in data:
        raise ConfigError(f"{path} does not look like a google-services.json file")
    return data


def find_android_client(google_services: dict, package_name: str) -> Optional[dict]:
    for client in google_services.get("client", []):
        info = client.get("client_info", {}).get("android_client_info", {})
        if info.get("package_name") == package_name:
            return client
    return None


def registered_packages(google_services: dict) -> List[str]:
    return [
        c.get("client_info", {}).get("android_client_info", {}).get("package_name", "?")
        for c in google_services.get("client", [])
    ]


def parse_web_config(path: Path) -> Dict[str, str]:
    """Accept JSON or the JS snippet from the console; return key -> value."""
    text = path.read_text("utf-8")
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return {str(k): str(v) for k, v in data.items() if v is not None}
    except json.JSONDecodeError:
        pass
    pairs = re.findall(r'["\']?(\w+)["\']?\s*:\s*["\']([^"\']*)["\']', text)
    if not pairs:
        raise ConfigError(f"{path}: could not find any key: \"value\" pairs")
    return {k: v for k, v in pairs}


def dart_fields(fields: List[tuple]) -> str:
    lines = [f"    {key}: '{value}'," for key, value in fields if value]
    return "\n".join(lines)


def build_android_fields(project: dict, client: dict) -> List[tuple]:
    api_keys = client.get("api_key") or []
    if not api_keys or not api_keys[0].get("current_key"):
        raise ConfigError("google-services.json: the Android client has no api_key")
    return [
        ("apiKey", api_keys[0]["current_key"]),
        ("appId", client["client_info"]["mobilesdk_app_id"]),
        ("messagingSenderId", project["project_number"]),
        ("projectId", project["project_id"]),
        ("databaseURL", project.get("firebase_url", "")),
        ("storageBucket", project.get("storage_bucket", "")),
    ]


def build_web_fields(project: dict, web: Optional[Dict[str, str]], warnings: List[str]) -> List[tuple]:
    web = web or {}
    project_id = web.get("projectId") or project["project_id"]
    if web and web.get("projectId") and web["projectId"] != project["project_id"]:
        warnings.append(
            f"web config projectId '{web['projectId']}' differs from google-services.json "
            f"projectId '{project['project_id']}'"
        )
    api_key = web.get("apiKey") or WEB_API_KEY_PLACEHOLDER
    app_id = web.get("appId") or WEB_APP_ID_PLACEHOLDER
    if api_key == WEB_API_KEY_PLACEHOLDER or app_id == WEB_APP_ID_PLACEHOLDER:
        warnings.append(
            "no --web-config given: web apiKey/appId are placeholders. Register a Web app in the "
            "Firebase console and re-run with --web-config <file> before building for the web."
        )
    return [
        ("apiKey", api_key),
        ("appId", app_id),
        ("messagingSenderId", web.get("messagingSenderId") or project["project_number"]),
        ("projectId", project_id),
        ("authDomain", web.get("authDomain") or f"{project_id}.firebaseapp.com"),
        ("databaseURL", web.get("databaseURL") or project.get("firebase_url", "")),
        ("storageBucket", web.get("storageBucket") or project.get("storage_bucket", "")),
        ("measurementId", web.get("measurementId", "")),
    ]


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def resolve_app(app: str, google_services_src: Optional[Path]) -> dict:
    """Validate one app without writing anything; return what configure_app needs."""
    app_dir = REPO_ROOT / app
    if not app_dir.is_dir():
        raise ConfigError(f"unknown app '{app}' (expected one of {', '.join(DEFAULT_APPS)})")

    target_json = app_dir / "android" / "app" / "google-services.json"
    source_json = google_services_src if google_services_src is not None else target_json
    google_services = load_google_services(source_json)
    package_name = read_application_id(app_dir)
    client = find_android_client(google_services, package_name)
    if client is None:
        raise ConfigError(
            f"[{app}] {source_json} has no Android client for package "
            f"'{package_name}'. Registered packages: {', '.join(registered_packages(google_services)) or 'none'}.\n"
            f"   -> In the Firebase console add an Android app with package name '{package_name}' "
            f"(or change applicationId in {app}/android/app/build.gradle), then download "
            f"google-services.json again. Nothing was modified."
        )
    return {
        "app": app,
        "app_dir": app_dir,
        "target_json": target_json,
        "google_services": google_services,
        "package_name": package_name,
        "client": client,
    }


def configure_app(resolved: dict, google_services_src: Optional[Path], web_config: Optional[Dict[str, str]]) -> List[str]:
    app: str = resolved["app"]
    app_dir: Path = resolved["app_dir"]
    target_json: Path = resolved["target_json"]
    google_services: dict = resolved["google_services"]
    package_name: str = resolved["package_name"]
    client: dict = resolved["client"]
    project = google_services["project_info"]

    if google_services_src is not None:
        target_json.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(google_services_src, target_json)
        print(f"[{app}] copied {google_services_src} -> {target_json.relative_to(REPO_ROOT)}")

    warnings: List[str] = []
    if not project.get("firebase_url"):
        warnings.append(
            "google-services.json has no firebase_url: create the Realtime Database in the Firebase "
            "console first, then download google-services.json again (the apps need it)."
        )
    if not project.get("storage_bucket"):
        warnings.append("google-services.json has no storage_bucket: enable Firebase Storage, then re-download.")

    dart = DART_TEMPLATE.format(
        app_name=app,
        project_id=project["project_id"],
        package_name=package_name,
        web_fields=dart_fields(build_web_fields(project, web_config, warnings)),
        android_fields=dart_fields(build_android_fields(project, client)),
    )
    out = app_dir / "lib" / "firebase_options.dart"
    out.write_text(dart, "utf-8", newline="\n")
    print(f"[{app}] wrote {out.relative_to(REPO_ROOT)}  (project: {project['project_id']}, package: {package_name})")
    return [f"[{app}] {w}" for w in warnings]


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--google-services", type=Path, metavar="PATH",
                        help="google-services.json downloaded from the Firebase console; copied into every selected app")
    parser.add_argument("--web-config", type=Path, metavar="PATH",
                        help="Firebase Web app config (JSON or the JS snippet from the console)")
    parser.add_argument("--apps", nargs="+", default=DEFAULT_APPS, metavar="APP",
                        help=f"apps to configure (default: {' '.join(DEFAULT_APPS)})")
    args = parser.parse_args(argv)

    try:
        web_config = parse_web_config(args.web_config) if args.web_config else None
        # Validate every app first so a problem with one app never leaves the repo half-updated.
        resolved = [resolve_app(app, args.google_services) for app in args.apps]

        warnings: List[str] = []
        for item in resolved:
            warnings += configure_app(item, args.google_services, web_config)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  - {w}")
    print("\nDone. Review `git diff`, then commit google-services.json and lib/firebase_options.dart.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
